Update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -312,9 +312,11 @@ jobs:
         export USE_CCACHE=1 \
         mkdir WORKSPACE && cd WORKSPACE && repo init -u https://github.com/PixelBuildsROM/android_manifest -b unity --depth=1 && rm -rf device/xiaomi/merlin vendor/xiaomi/merlin device/xiaomi/merlin-kernel && git clone https://github.com/nuuwy0/local_manifest .repo/local_manifests --depth 1 && /opt/crave/resync.sh \
 
-        if [ $? -ne 0 ]; then \
-         echo "Error: repo sync failed" \
-         fi \
+       if [ ! \$? == 0 ]; then \
+          curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }}; \
+          echo "Git clone failed, downloading through curl instead..."; \
+        fi \
+
 
         make installclean && \
         ./pb-build.sh merlin"
